### ISSUE TITLE
xpp3:xpp3:jar:clean:1.1.4c is not available in any included repository

### ISSUE THREAD

**Issue by si0ls** [collectionspace/services#359]
Hi 👋 

I'm trying to create a Dockerfile (and docker-compose) to build and run Collection Space.

I'm encountering an error during the build with the xpp3 artefact, whose `clean` variant doesn't exist on any repository embedded with the project.

```
[ERROR] Failed to execute goal on project org.collectionspace.services.common: Could not resolve dependencies for project org.collectionspace.services:org.collectionspace.services.common:jar:7.2.0-SNAPSHOT: The following artifacts could not be resolved: xpp3:xpp3:jar:clean:1.1.4c (absent): Could not transfer artifact xpp3:xpp3:jar:clean:1.1.4c from/to maven-default-http-blocker (http://0.0.0.0/): Connect to 0.0.0.0:80 [/0.0.0.0] failed: Connection refused (Connection refused) -> [Help 1]
```

I found the following repository which still contains the `xpp3:xpp3:jar:clean:1.1.4c` artefact.

```xml
<repository>
	<id>maven-ja</id>
	<name>ja-internal</name>
	<url>https://www.juntadeandalucia.es/madeja/repositoriodelibrerias/ja-internal</url>
</repository>
```

Is there a way of solving this problem permanently?
I'm not comfortable with the Java environment, so I don't feel able to suggest a PR to fix the problem in a clean way.

**Comment by ray-lee** [comment]
Hi,
What version of maven are you using? It looks like this can happen starting with 3.8. You may be able to use an older version until we can find a solution.

**Comment by si0ls** [comment]
Hi,
I'm using maven 3.9.3, it is the only version provided by the [official docker maven image](https://hub.docker.com/_/maven).
Thanks for your answer, I'll try with maven 3.7

Since I plan to create a prod-ready Dockerfile to deploy Collection Space, if successful, are you interested by a contribution on cspace-installer or another repo?

**Comment by ray-lee** [comment]
Thanks for the offer, but we're actually not going to continue maintaining cspace-installer or any automated installer. It's the sort of thing we're going to leave up to the community. But I hope you'll make your work available for people to use.

**Comment by ray-lee** [comment]
The `xpp3:xpp3:jar:clean:1.1.4c `artifact has been added to the CollectionSpace maven repo.
